language: go

go:
- 1.16

# https://golang.org/doc/install/source#environment
env:
- BUILD_GOOS=darwin BUILD_GOARCH=amd64
- BUILD_GOOS=linux BUILD_GOARCH=amd64

before_install:
- echo " >>> downloading dep"
- go get -u github.com/golang/dep/cmd/dep

install:
- echo " >>> downloading dependencies"
- dep ensure
- dep status

before_script:
- echo " >>> preparing build informations"
- PROJECT_NAME=$( echo ${TRAVIS_REPO_SLUG} | cut -d "/" -f 2 )
- OUTPUT_NAME=${PROJECT_NAME}-${BUILD_GOOS}-${BUILD_GOARCH}
- |
  APP_VERSION=${TRAVIS_BRANCH}-$( git rev-parse --short ${TRAVIS_COMMIT} )
  PRE_RELEASE="false"
  if [ -n "${TRAVIS_TAG}" ]; then
    APP_VERSION=${TRAVIS_TAG}
    semver=( ${APP_VERSION//./ } )
    major="${semver[0]}"
    if [ $major -lt 1 ]; then
      PRE_RELEASE="true"
    fi
  fi
- echo " >>> build version ${APP_VERSION}"

script:
- echo " >>> Building ${OUTPUT_NAME}"
- env CGO_ENABLED=0 GOOS=${BUILD_GOOS} GOARCH=${BUILD_GOARCH} go build -a -installsuffix cgo -x -ldflags "-X main.version=${APP_VERSION}" -o ${OUTPUT_NAME} cmd/*.go
- tar -cvzf ${OUTPUT_NAME}.tar.gz ${OUTPUT_NAME}

before_deploy:
- mkdir -p build/${TRAVIS_TAG}
- shasum -a 256 ${OUTPUT_NAME}.tar.gz | awk '{print $1}' > build/${TRAVIS_TAG}/${OUTPUT_NAME}.tar.gz.sha265

deploy:
- provider: releases
  api_key: ${GITHUB_API_KEY}
  prerelease: ${PRE_RELEASE}
  file: 
  - ${OUTPUT_NAME}.tar.gz
  skip_cleanup: true
  on:
    tags: true

